### ISSUE TITLE
Control image pull policy

### ISSUE THREAD

**Issue by sanmai-NL** [loft-sh/devpod-provider-kubernetes#17]
I didn't find a way to specify the image pull policy.  Starting a dev container fails for me using a workstation-local Kubernetes deployment.

 ```$ devpod up . --debug --devcontainer-path .devcontainer/pttctool/devcontainer.json --ide vscode
GET https://index.docker.io/v2/library/mylocalimage/manifests/development: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/mylocalimage Type:repository]]
```

**Comment by FabianKramm** [comment]
@sanmai-NL thanks for creating this issue! Sorry for the delay, most of our engineers were on vacation the last 2 weeks. Regarding your issue: mhhh seems like we didn't account for that case, is there more log info to this?

**Comment by sanmai-NL** [comment]
Well, to be clear, pulling should fail in this case. So I expect the logs not to be of much help. The problem is I can't configure the pull policy.

**Comment by pascalbreuninger** [comment]
@sanmai-NL the newer versions of this provider should merge the image pull policy of the `POD_MANIFEST_TEMPLATE` option into the pod
