### ISSUE TITLE
Make pod-running-waiting timeout configurable  

### ISSUE THREAD

**Issue by pbialon** [loft-sh/devpod-provider-kubernetes#5]
**Description**

Users have been experiencing issues with timeouts when working with the cluster autoscaler.

In the current setup, if the node selector setting triggers the autoscaler, the system often times out at the devpod level. This is particularly evident in environments where autoscaler response times are slower. Making the timeout user-configurable can help alleviate these issues and provide a more flexible solution for varied user environments.

**Proposed solution**

Introduce a configurable timeout option for users.

**Alternative solutions**

Static Extension: Increase the default timeout value, though this is not a one-size-fits-all solution.

**Additional context**

Slack discussion: https://loft-sh.slack.com/archives/C056ZDZPJ4W/p1694654884948429

**Comment by cameronraysmith** [comment]
This appears to be set at https://github.com/loft-sh/devpod-provider-kubernetes/blob/cfc382d9ef6acd0c85c59026d6d89bc9949b9b65/pkg/kubernetes/wait.go#L31
