### ISSUE TITLE
Once a workspace is created, the devcontainer spec can not be changed without recreating it

### ISSUE THREAD

**Issue by doctorpangloss** [loft-sh/devpod-provider-kubernetes#57]
1. Create a workspace for a python project
2. Observe the default devcontainer will be a python 3.12 image rather than 3.11, so there is poor compatibility.
3. Try to change the image in the devcontainer.json
4. Observe there is no procedure besides completely deleting and re-creating the workspace to change the container image.

I don't view this as a serious limitation, overall I am stunned how well everything works.

**Comment by pascalbreuninger** [comment]
Hey @doctorpangloss, I've totally missed this issue 😅 
The reason why this won't work without recreating the workspace is that we create the pod with the image you've specified in your devcontainer.json or build it in the pod and then pivot root to the new local image. 
From DevPods perspective the PVC is the workspace, not the pod
