### ISSUE TITLE
devpod delete kubernetes-pod (infinite wait, pending state)

### ISSUE THREAD

**Issue by solesensei** [loft-sh/devpod-provider-kubernetes#60]
How can I delete a workspace on a pod that hasn't been created yet, but is in the `pending` state?

I tried using the command:

```bash
devpod delete kubernetes-pod --grace-period 5
```

But it didn't work. The devpod just displays the message: `Waiting, since pod 'devpod-default-ku-26d16' is starting`.

It seems the `--force` option is also not working.

**Comment by pascalbreuninger** [comment]
Hey @solesensei, thanks for opening this issue. 
Which state is the pod in? 
You should be able to delete the workspace after deleting the pod. We should build better controls for this into DevPod itself though

**Comment by solesensei** [comment]
You can't delete a workspace if the pod is in any state except "ready". If you delete the pod directly, then devpod deletes workspace without problems.

**Comment by solesensei** [comment]
I guess you don't need to actually wait until ready, before calling kubectl delete.

**Comment by pascalbreuninger** [comment]
> I guess you don't need to actually wait until ready, before calling kubectl delete.

Yeah, it looks like the problem is core DevPod that tries to ensure the workspace runs before calling the providers `delete`
